### ISSUE TITLE
/v2/account/wallet -- gems totally broken

### ISSUE THREAD

**Issue by lye** [arenanet/api-cdi#274]
We moved where gem quantities live and the backend component that services API requests wasn't updated.

Whoops.

**Comment by Archomeda** [comment]
*(keeping this up-to-date)*

Recently it has been fixed for most people apparently [(ref 1)](https://gitter.im/arenanet/api-cdi?at=57f7fa830aa72e3c5be2b9f6) [(ref 2)](https://gitter.im/arenanet/api-cdi?at=57f7fac54fde7203141aa6a9).

But mine are still inaccurate [(ref)](https://gitter.im/arenanet/api-cdi?at=57fcc8ebdfe82a365b168336). And it's unknown why [(ref)](https://gitter.im/arenanet/api-cdi?at=57fdc79570fcb5db0c4ccdd9).
At the time of writing, my gems should be at 800. But the [API still says 1028](https://api.guildwars2.com/v2/account/wallet?access_token=CD681A99-1EB2-FB43-8C35-516A42AC10EC6479D63A-09DB-419C-8AEA-FAC7C827D191), which was the amount I had a long time ago (probably at the end of 2015 - beginning of 2016).

**Comment by queicherius** [comment]
Someone just wrote me with another report of this issue, so either it's still broken or it broke again. 😢

**Comment by tivac** [comment]
It's probably a caching thing given @Archomeda's experience. This original issue is resolved, at least. Further issues should be opened up on a case-by-case basis.
